### PR TITLE
Set timeout for keeplive

### PR DESCRIPTION
**Pull request by LiChengZiMu**
Etcd server will elect new leader, when leader(client) lost all message with etcd server permanently， but origin leader can't know about it.

### CODE REVIEW

**Comment by LiChengZiMu** [comment]
> Thanks for the work, but I think the timeout feature needs more effort and should be available across all APIs.
> 
> I won't merge this PR at this time, but thanks for trying the idea and prompt the priority of the problem!

Because my project need this feature, I want know if the code changes by me will work well, Thanks

**Comment by sighingnow** [comment]
Hi @LiChengZiMu,

May I get more idea bebind the adding of timeout to keepalive? The `refresh()` action happens in the background thread and shouldn't have any effect in the main thread.

I cannot see why we need a timeout inside the `refresh()` operation. Could you give more detail about the iseue that you encountered?

Thanks!

**Comment by LiChengZiMu** [comment]
> Thanks

1. 我遇到的问题是我需要一个keepailve客户端超时机制，否则我彻底中断网络连接(非重启场景，此时tcp连接不会关闭)  
```

sudo iptables -A OUTPUT -p tcp --dport 2379 -j DROP  
sudo iptables -A OUTPUT -p tcp --sport 2379 -j DROP  

```
会导致keepalive消息发送不到etcd，然后leader key超时失效，但是超时的response也没办法被收到，此时一个已经失去主的节点，没办法感知自己失去了主。    
当然这个问题或许可以通过设置激进的grpc keepalive策略来解决。  
image  
grpc_args.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 1000);    
grpc_args.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 5000);    
但是不知道如此设置是否有意料之外的副作用

**Comment by sighingnow** [comment]
Ok.

但是keepalive的refresh是一个后台线程在自动执行，你也没办法monitor它超时的response？

**Comment by sighingnow** [comment]
> Ok.
> 
> 但是keepalive的refresh是一个后台线程在自动执行，你也没办法monitor它超时的response？

I see. 你是依赖keepalive的那个handler来得知当前的refresh失败了么

**Comment by sighingnow** [comment]
A bit better implementation has been added in #135.

**Pull request closed without merging**
